[project]
dataPersistence = true
enable_telemetry = true
user_env = []
session_timeout = 3600
user_session_timeout = 1296000  # 15 days
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true
data_persistence = true

[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

[features.audio]
sample_rate = 24000

[features.mcp.sse]
enabled = true

[features.mcp.stdio]
enabled = true
allowed_executables = [ "npx", "uvx" ]

[UI]
name = "ClimateGPT Assistant"
description = "Your friendly assistant for all things climate change in Uganda 🇺🇬"
default_theme = "dark"
cot = "full"
default_sidebar_state = "open"  # Sidebar should be open by default

# Optional: Add your logo here if you have one!
# custom_meta_image_url = "https://yourdomain.com/logo.png"

[meta]
generated_by = "2.4.400"
